<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevWebSecDemo.Entities\DevWebSecDemo.Entities.csproj" />
    <ProjectReference Include="..\DevWebSecDemo.Providers\DevWebSecDemo.Providers.csproj" />
  </ItemGroup>

</Project>
